steps:
- name: 'gcr.io/sodium-sublime-243008/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://104.198.153.106:9000'
    - '-Dsonar.login=6368b35ae02c92d067fde1877f7b9f91941fe4d7'
    - '-Dsonar.projectKey=sample-project'
    - '-Dsonar.sources=.'
tags: ['cloud-builders-community']
